<?php

/**
 * prefix_comTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class prefix_comTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object prefix_comTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('prefix_com');
    }
}