<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/02/09 12:33:14

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=cmovil-cl',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
