<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/02/09 14:50:09

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=cmovil-cl',
  'username' => 'root',
  'password' => 'lagoranco1809',
  'name' => 'doctrine',
)),);
