<?php
// auto-generated by sfAutoloadConfigHandler
// date: 2011/02/10 14:14:09
return array(

  // sfDoctrinePlugin_module_libs

  // sfDoctrinePlugin_lib
  'sfdoctrinecli' => '/media/D/www/cmovil-cl/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/cli/sfDoctrineCli.class.php',
  'sfdoctrineconnectionlistener' => '/media/D/www/cmovil-cl/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionListener.class.php',
  'sfdoctrineconnectionprofiler' => '/media/D/www/cmovil-cl/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionProfiler.class.php',
  'sfdoctrinedatabase' => '/media/D/www/cmovil-cl/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineDatabase.class.php',
  'sfwebdebugpaneldoctrine' => '/media/D/www/cmovil-cl/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/debug/sfWebDebugPanelDoctrine.class.php',
  'sfformdoctrine' => '/media/D/www/cmovil-cl/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/form/sfFormDoctrine.class.php',
  'sfformfilterdoctrine' => '/media/D/www/cmovil-cl/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/form/sfFormFilterDoctrine.class.php',
  'sfdoctrinecolumn' => '/media/D/www/cmovil-cl/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineColumn.class.php',
  'sfdoctrineformfiltergenerator' => '/media/D/www/cmovil-cl/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormFilterGenerator.class.php',
  'sfdoctrineformgenerator' => '/media/D/www/cmovil-cl/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormGenerator.class.php',
  'sfdoctrinegenerator' => '/media/D/www/cmovil-cl/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineGenerator.class.php',
  'swift_doctrinespool' => '/media/D/www/cmovil-cl/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/mailer/Swift_DoctrineSpool.class.php',
  'sfdoctrinepager' => '/media/D/www/cmovil-cl/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/pager/sfDoctrinePager.class.php',
  'sfdoctrinerecord' => '/media/D/www/cmovil-cl/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecord.class.php',
  'sfdoctrinerecordi18nfilter' => '/media/D/www/cmovil-cl/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecordI18nFilter.class.php',
  'sfdoctrineroute' => '/media/D/www/cmovil-cl/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRoute.class.php',
  'sfdoctrineroutecollection' => '/media/D/www/cmovil-cl/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRouteCollection.class.php',
  'sfdoctrineexception' => '/media/D/www/cmovil-cl/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/sfDoctrineException.class.php',
  'sfdoctrinebasetask' => '/media/D/www/cmovil-cl/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBaseTask.class.php',
  'sfdoctrinebuilddbtask' => '/media/D/www/cmovil-cl/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildDbTask.class.php',
  'sfdoctrinebuildfilterstask' => '/media/D/www/cmovil-cl/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFiltersTask.class.php',
  'sfdoctrinebuildformstask' => '/media/D/www/cmovil-cl/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFormsTask.class.php',
  'sfdoctrinebuildmodeltask' => '/media/D/www/cmovil-cl/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildModelTask.class.php',
  'sfdoctrinebuildschematask' => '/media/D/www/cmovil-cl/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSchemaTask.class.php',
  'sfdoctrinebuildsqltask' => '/media/D/www/cmovil-cl/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSqlTask.class.php',
  'sfdoctrinebuildtask' => '/media/D/www/cmovil-cl/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildTask.class.php',
  'sfdoctrinecleanmodelfilestask' => '/media/D/www/cmovil-cl/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCleanModelFilesTask.class.php',
  'sfdoctrineconfiguredatabasetask' => '/media/D/www/cmovil-cl/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineConfigureDatabaseTask.class.php',
  'sfdoctrinecreatemodeltables' => '/media/D/www/cmovil-cl/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCreateModelTablesTask.class.php',
  'sfdoctrinedatadumptask' => '/media/D/www/cmovil-cl/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataDumpTask.class.php',
  'sfdoctrinedataloadtask' => '/media/D/www/cmovil-cl/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataLoadTask.class.php',
  'sfdoctrinedeletemodelfilestask' => '/media/D/www/cmovil-cl/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDeleteModelFilesTask.class.php',
  'sfdoctrinedqltask' => '/media/D/www/cmovil-cl/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDqlTask.class.php',
  'sfdoctrinedropdbtask' => '/media/D/www/cmovil-cl/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDropDbTask.class.php',
  'sfdoctrinegenerateadmintask' => '/media/D/www/cmovil-cl/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateAdminTask.class.php',
  'sfdoctrinegeneratemigrationsdbtask' => '/media/D/www/cmovil-cl/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDbTask.class.php',
  'sfdoctrinegeneratemigrationsdifftask' => '/media/D/www/cmovil-cl/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDiffTask.class.php',
  'sfdoctrinegeneratemigrationsmodelstask' => '/media/D/www/cmovil-cl/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsModelsTask.class.php',
  'sfdoctrinegeneratemigrationtask' => '/media/D/www/cmovil-cl/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationTask.class.php',
  'sfdoctrinegeneratemoduleforroutetask' => '/media/D/www/cmovil-cl/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleForRouteTask.class.php',
  'sfdoctrinegeneratemoduletask' => '/media/D/www/cmovil-cl/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleTask.class.php',
  'sfdoctrineinsertsqltask' => '/media/D/www/cmovil-cl/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineInsertSqlTask.class.php',
  'sfdoctrinemigratetask' => '/media/D/www/cmovil-cl/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineMigrateTask.class.php',
  'sftesterdoctrine' => '/media/D/www/cmovil-cl/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/test/sfTesterDoctrine.class.php',
  'sfvalidatordoctrinechoice' => '/media/D/www/cmovil-cl/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineChoice.class.php',
  'sfvalidatordoctrineunique' => '/media/D/www/cmovil-cl/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineUnique.class.php',
  'sfwidgetformdoctrinechoice' => '/media/D/www/cmovil-cl/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/widget/sfWidgetFormDoctrineChoice.class.php',

  // project
  'baseprefixcomformfilter' => '/media/D/www/cmovil-cl/lib/filter/doctrine/base/BasePrefixComFormFilter.class.php',
  'baseprefix_comformfilter' => '/media/D/www/cmovil-cl/lib/filter/doctrine/base/Baseprefix_comFormFilter.class.php',
  'baseformfilterdoctrine' => '/media/D/www/cmovil-cl/lib/filter/doctrine/BaseFormFilterDoctrine.class.php',
  'prefixcomformfilter' => '/media/D/www/cmovil-cl/lib/filter/doctrine/PrefixComFormFilter.class.php',
  'prefix_comformfilter' => '/media/D/www/cmovil-cl/lib/filter/doctrine/prefix_comFormFilter.class.php',
  'baseform' => '/media/D/www/cmovil-cl/lib/form/BaseForm.class.php',
  'baseprefixcomform' => '/media/D/www/cmovil-cl/lib/form/doctrine/base/BasePrefixComForm.class.php',
  'baseprefix_comform' => '/media/D/www/cmovil-cl/lib/form/doctrine/base/Baseprefix_comForm.class.php',
  'baseformdoctrine' => '/media/D/www/cmovil-cl/lib/form/doctrine/BaseFormDoctrine.class.php',
  'prefixcomform' => '/media/D/www/cmovil-cl/lib/form/doctrine/PrefixComForm.class.php',
  'prefix_comform' => '/media/D/www/cmovil-cl/lib/form/doctrine/prefix_comForm.class.php',

  // project_model
  'baseprefixcom' => '/media/D/www/cmovil-cl/lib/model/doctrine/base/BasePrefixCom.class.php',
  'baseprefix_com' => '/media/D/www/cmovil-cl/lib/model/doctrine/base/Baseprefix_com.class.php',
  'prefixcom' => '/media/D/www/cmovil-cl/lib/model/doctrine/PrefixCom.class.php',
  'prefixcomtable' => '/media/D/www/cmovil-cl/lib/model/doctrine/PrefixComTable.class.php',
  'prefix_com' => '/media/D/www/cmovil-cl/lib/model/doctrine/prefix_com.class.php',
  'prefix_comtable' => '/media/D/www/cmovil-cl/lib/model/doctrine/prefix_comTable.class.php',

  // application
  'myuser' => '/media/D/www/cmovil-cl/apps/frontend/lib/myUser.class.php',

  // modules
);
